sms_core/sms_api/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter 

from .views import *

app_name = 'sms_api'

public_urls_v1 = [
    path('happy_message', return_happy_message, name='happy_message'),
]

urlpatterns = [
    path('api/public/v1/', include((public_urls_v1, 'api'), namespace='public_v1')),
]

sms_core/sms_backend/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from .views import *

app_name = 'sms_backend'

# Pages
urlpatterns = [
    path('' ,TemplateView.as_view(template_name='index.html'), name='index'),
    path('about' ,TemplateView.as_view(template_name='about.html'), name='about'),
    path('cpp_project' ,TemplateView.as_view(template_name='cpp_project.html'), name='cpp_project'),
    path('python_project' ,TemplateView.as_view(template_name='python_project.html'), name='python_project'),
    path('cv' ,TemplateView.as_view(template_name='cv.html'), name='cv'),
    path('hobbies' ,TemplateView.as_view(template_name='hobbies.html'), name='hobbies'),
    path('programming' ,TemplateView.as_view(template_name='programming.html'), name='programming'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Internal endpoints
urlpatterns += [
    path("show_latest_pdf/<str:tag>/", pdf_view, name="show_latest_pdf")
]

sms_core/sms_core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sms_backend.urls')),
    path('', include('sms_api.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

sms_core/sms_api/models.py
from django.db import models

# Create your models here.

sms_core/sms_backend/models.py
from django.db import models

# Create your models here.

class Files(models.Model):

    class Meta:
        get_latest_by = 'upload_date'

    file = models.FileField()
    tag = models.CharField(max_length=10, blank=True, null=True)
    upload_date = models.DateTimeField(auto_now_add=True)

    

sms_core/sms_api/views.py
from sms_backend.models import *
from rest_framework import viewsets, mixins, status
from rest_framework.response import Response
from rest_framework.decorators import api_view, parser_classes, action
from rest_framework.parsers import FileUploadParser, MultiPartParser
from oauth2_provider.decorators import protected_resource

# Create your views here.
class FileManagementViewset(viewsets.ModelViewSet):
    """
    This will be how files are uploaded and managed by the server
    """
    pass

@protected_resource()
@api_view(["GET"])
def return_happy_message(request):
    message = {
        'detail' : 'Thanks for hitting this endpoint'
    }
    return Response(data=message, status=status.HTTP_200_OK)

sms_core/sms_backend/views.py
from django.shortcuts import render
from django.http import HttpResponseNotFound, HttpResponseForbidden, FileResponse , HttpResponse, Http404
from .models import *

# Create your views here.

def pdf_view(request, tag):
    file = Files.objects.filter(tag=tag).latest()
    try:
        return FileResponse(open(file.file.path, 'rb'), content_type = 'application/pdf')
    except FileNotFoundError:
        raise Http404

sms_core/sms_backend/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<main>
	<div class="jumbotron">
		<div class="container">
			<h1>About Me </h1>
			<p>Here you will find a brief summary of my life so far.</p><br>
			<a href="{% url 'sms_backend:cv' %}" class="btn-main"> Next Page</a>
		</div>
	</div>
</main>

<section class="supporting">
	<div class="left-box">
		<div class="item">
			<h4>Early life &emsp; &emsp; 1990-2010</h4>
			<p>Until I moved to Brighton for university, I had only ever lived in one house, which was my parents home
				in West London. With both my parents having Polish ancestry my first language was naturally Polish, and
				only learned English when I went to elementary school. Sadly my Polish never recovered from being
				dethroned as my native language, although I am still conversationally fluent, and have taught myself to
				read Polish to some extent.
			</p><br>
			<p> My first school was called Hill House and it was spread out around Sloan Square and Knightsbridge. This
				was where I spent my time untill my 13+ exams, which I skipped as I had already gotten a place at my
				secondary school, City of London Boys School.
			</p><br>
			<p> City of London was where I took my GCSEs and A-levels. My GCSEs included all the required modules with
				Russian as my chosen language. For my AS-levels I took Maths, Physics, Art, and Philosophy, dropping the
				latter for my A-levels.
			</p><br>
			<p>After my A levels I took some time to work in various locations. The first of these was working a retail
				assistant at Currys. This was follwed by an extremely informative time working as a chef. Initially I
				thought to take a degree in architecture, but instead decided to follow into physics instead, and found
				a place at Sussex University in Brighton.
			</p>
		</div>
		<div class="item">
			<img src="/static/Images/aboutme-earlylife.jpg" alt="Early Life">
		</div>
	</div>
</section>

<section class="supporting">
	<div class="right-box">
		<div class="item">
			<img src="/static/Images/aboutme-university.jpg" alt="University">
		</div>
		<div class="item">
			<h4>University &emsp; &emsp; 2010-2015</h4>
			<p>At Sussex I developed many of the skills I have today. I greatly enjoyed my degree and all the courses in
				it.
			</p><br>
			<p>While working through my studies I took part in both student council and took charge of the physics
				society at Sussex. This gave me ample experience organising a multitude of events and coordinating
				people to preassigned tasks.
			</p><br>
			<p> Once my undergraduate degree had been completed I decided I wanted to do further study, and as my
				interest up until that point had always been in the more theoretical subjects, I chose to find a
				theoretical particle physics project. At the time the Higgs Boson had not yet been confirmed and
				Supersymmetry was still a hopeful theory with results possibly coming in within the next yeat. This
				changed during my Masters and it is quite clear now that if Supersymmetry exists, it is not how it was
				theorised in my paper.
			</p><br>
			<p>One thing that stood out to me was how disconnected I felt to the subject matter, and as such decided to
				not follow on to a PhD in theoretical physics. I decided to look for something more practical after I
				left.
			</p>
		</div>
	</div>
</section>

<section class="supporting">
	<div class="left-box">
		<div class="item">
			<h4>Post-University &emsp; &emsp; 2015-2019</h4>
			<p>My initial desire was to try to find more details on the emerging technology of quantum computation.
				Finding a PhD opportunity or really any sort of professional placement in the area proved challenging
				with my theoretical background. Thus I endevoured to keep working in laboratories and try to develop the
				skills needed to research this area.
			</p><br>
			<p>This led me back to London where I first found employment as a chef for a few hectic months in summer.
				After this I found steady employment as a science technician at 2 different schools. While these jobs
				were enjoyable and gave me a lot of experience with health and safety in laboratories, I still wanted to
				return to university to continue my studies. By now machine learning had taken off in the public
				zeitgeist and it left me with some interesting questions about its applications in quantum computing.
			</p><br>
			<p>I decided to apply for a Masters in quantum communication at UCL with a focus on using machine learning
				on quantum systems.
			</p>
		</div>
		<div class="item">
			<img src="/static/Images/aboutme-postuniversity.jpg" alt="Post University">
		</div>
	</div>
</section>

<section class="supporting">
	<div class="right-box">
		<div class="item">
			<img src="/static/Images/aboutme-university2.jpg" alt="University 2.0">
		</div>
		<div class="item">
			<h4>University 2.0 &emsp; &emsp; 2019-2010</h4>
			<p>While my previous Masters left me with only theoretical skills, this course gave me a fantastic
				opportunity to practice my coding ability. Prior to this course I had always enjoyed the coding I had
				done, but it was quite limited in its scope. Here I had the opportunity to really spread my wings with
				the problems and projects I took on.
			</p><br>
			<p>In the first term I had to find my own project supervisor as the university was overbooked, and I found
				one that was willing to take me on with a project that involved using machine learning techniques on
				quantum systems. I also found two more courses that taught me about high performance computing and
				general coding practices such as project control through GitHub.
			</p><br>
			<p>I learned that the things I wanted to achieve in machin learning were completely doable without the use
				of qubits, although I had the ability to extend these techniques to them if they became commercially
				viable in the future.
			</p><br>
			<p>After finishing my degree I kept up and further improved my coding skills as well as learned new
				subjects. This was in combiantion with looking for employment as a programmer.
			</p>
		</div>
	</div>
</section>

<section class="supporting">
	<div class="left-box">
		<div class="item">
			<h4>Work at Mo-Sys &emsp; &emsp; 2021-Present</h4>
			<p>After university I found employment Mo-Sys Engineering as a python developer. My role here was to work on
				their cloud rendering system. In this role I have had experience working with AWS, creating and
				maintaining various websites, Oauth authorisation techniques and have had a chance to work with Unreal
				engine.
			</p>
		</div>
		<div class="item">
			<img src="/static/Images/aboutme-mosys.jpg" alt="University 2.0">
		</div>
	</div>
</section>

{% endblock %}

sms_core/sms_backend/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block links %}
    <link href='https://fonts.googleapis.com/css?family=Raleway:400, 600' rel='stylesheet' type='text/css'>
    <link href="{% static 'favicon.ico' %}" rel="icon">
    <link href="{% static 'style.css' %}" rel='stylesheet'>
    {% endblock %}
</head>

<body>
{% block header %}

<header>
    <nav>
        <ul>
            <li><a href="{% url 'sms_backend:index' %}" >Home</a></li>
            <li><a href="{% url 'sms_backend:about' %}" >About me</a></li> 
            <li><a href="{% url 'sms_backend:cv' %}" > Online CV</a></li>
            <li><a href="{% url 'sms_backend:programming' %}" >Programming</a></li>
            <li><a href="{% url 'sms_backend:hobbies' %}" >Hobbies</a></li> 
            <li><a href="{% url 'sms_backend:python_project' %}" > Python Project </a></li> 
            <li><a href="{% url 'sms_backend:cpp_project' %}" > C++ Project </a></li>
        </ul>
    </nav>
</header>

{% endblock %}

{% block content %}{% endblock %}

{% block footer %}

<footer>
    <div class="container">
        <p>&copy; Contact info; Email: <a href = "mailto: sandromarcus@hotmail.co.uk">sandromarcus@hotmail.co.uk</p>
    </div>
</footer>

{% endblock %}

</body>
</html>

sms_core/sms_backend/templates/cpp_project.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<main>
	<div class="jumbotron">
		<div class="container">
			<h1>Un-named C++ Project</h1>
			<a href="{% url 'sms_backend:index' %}" class="btn-main"> Start Again</a>
		</div>
	</div>
</main>

<section class="supporting">
	<div class="container">
		<h3>About The Program</h3>
		<p> write about the program a bit here</p>
		<h4>Objectives of Program</h4>
		<ul>
			<li>To be able to build using blocks</li>
			<li>To be able to run around a world</li>
			<li>To be able to randomly generate and save a world</li>
			<li>To be able to play with friends</li>
		</ul>
	</div>
</section>

<section class="supporting">
	<div class="container">
		<h3>Current status of Program</h3>
		<p>Here is the github link to the current project</p><br>
		<a href="" class="btn-main" target="_blank"> GitHub</a>
		<h4>Recent Changelog</h4>
		<ul>
			<li>None yet</li>
		</ul>
		<h4>To do List</h4>
		<ul>
			<li>Start Program</li>
			<li>v1.0 simple game in 2d</li>
			<li>v2.0 simple game in 3d</li>
			<li>v3.0 online multiplayer</li>
			<li>v4.0 launcher with website integration to track accounts</li>
			<li>v5.0 work on graphics and gpu proccessing/optimsations</li>
		</ul>
	</div>
</section>

{% endblock %}

sms_core/sms_backend/templates/hobbies.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<main>
	<div class="jumbotron">
		<div class="container">
			<h1> My hobbies and interests </h1>
			<a href="{% url 'sms_backend:python_project' %}" class="btn-main"> Next Page</a>
		</div>
	</div>
</main>

<section class="supporting">
	<div class="left-box">
		<div class="item">
			<h4>Cooking</h4>
			<p>Most of the chefs I've met or read about have stories of how they cooked with a parental figure from a
				young age,
				which nurtured their interest in the subject. My interest came about from an almost entierly opposite
				direction. I have memories
				of making cakes when I was younger but my interest really started when I started cooking meals for
				myself in my mid-late teen years.
			</p><br>
			<p>This interest was given a golden opportunity shortly before university when I found a job as a kitchen
				porter at a North
				London trattoria. The hours were long and the journey took over an hour but it really fed into my
				passion as I was given the
				opportunity to assist in preparation and eventually took on a role more closely resembling a commis
				chef.
			</p><br>
			<P>However I eventually decided to stick with my decision to go to university instead of pursuing the
				culinary arts, although my interest
				in the subject remained and I spent the next few years developing more skills. Since then I have had a
				far less enjoyable stint
				as a chef but my enthusiasm for cooking has not diminished.
			</P><br>
			<p>I enjoy throwing semi-lavish dinner parties for friends and self-catering social events I organise. This
				is in addition to
				my much maligned determination to experiment with dishes. I can recall a specific time I forced myself
				and my partner to eat
				ham hocks for about two weeks while I perfected a recipe.
			</p>
		</div>
		<div class="item">
			<img src="/static/Images/hobbies-cooking.jpg" alt="Cooking">
		</div>
	</div>
</section>

<section class="supporting">
	<div class="right-box">
		<div class="item">
			<img src="/static/Images/hobbies-computers.jpeg" alt="Computers">
		</div>
		<div class="item">
			<h4>Computers</h4>
			<p>This was again a surprisingly late addition to my interests. My parents were never particularly computer
				literate and we
				only owned the one PC for many years. The first PC I had was probably in about 2004, at around the same
				time I got my first
				console, the PS2. I used the computer to run World of Warcraft, which it did not do a good job of.
			</p><br>
			<p>Thus started my interest in computers, or rather, the search to be able to play my games at a decent
				framerate. I bought a
				computer from a colleague while I worked at Currys and this served me well for a while. A few upgrades
				and assistances from friends
				carried me through until I got to university which is when I built my first computer.
			</p><br>
			<p>That computer lasted me for many years, although with notable additions of a full water loop after some
				not so educated choices
				in GPU. The image opposite is one of my miscalculations on my latest build, do not use coloured coolant,
				it will stain everything.
			</p><br>
			<p>On top of building computers for myself I have also helped my friends and family build their own, most
				notably maintaining my partner's
				current rig.
			</p>
		</div>
	</div>
</section>

<section class="supporting">
	<div class="left-box">
		<div class="item">
			<h4>Artistic Endevours</h4>
			<p>At secondary school I took a real interst in art, achieving a 100% score on my art GCSE. While I took a
				very different path
				in university and science in general, I still like exploring my creative side on occasion.
			</p><br>
			<p>One of these is a hobby of painting miniatures, of which I have a sizable collection. Perhaps one day I
				will have the space to
				display them.
			</p><br>
			<p>Pictured opposite was my custom paintjob for my PS4 controller, which still works to this day.</p>
			<br>
			<p>While not artistically creative, I do creative writing for my D&D campaigns, which involves writing
				characters, stories, events and
				more.</p>
		</div>
		<div class="item">
			<img src="/static/Images/hobbies-controller.jpg" alt="Controller">
		</div>
	</div>
</section>

<section class="supporting">
	<div class="right-box">
		<div class="item">
			<img src="/static/Images/hobbies-gaming.jpg" alt="Gaming">
		</div>
		<div class="item">
			<h4>Gaming</h4>
			<p>As mentioned in the computer building section, I have a keen interest in games. My first memory of a game
				is probably playing the old
				space invaders on my father's computer when he wasn't using it. It was accessed through command line,
				before desktops existed, yes I'm old
				enough to have used a save icon.
			</p><br>
			<p>After this my next gaming related memory was playing Pokémon when it came out, along with their sequels.
				Thus owning a Gameboy and the
				GBA when it came out. This lead to my first RPG, Golden Sun and its sequel. After this I "tricked" my
				parents into buying me a Playstation
				on a family vacation to Ghana, although at this time I still wasnt playing games that often. This would
				change when I started playing World
				of Warcraft, and is probably where I can trace my current hobby interest to.
			</p><br>
			<p>Having my own computer allowed me to play much more frequently, and once I built my own functioning
				computer a few years later, I was free
				to really broaden my gaming horizons. These days I'm much more selective of the games that I play,
				selecting games that value my time invested
				in them. I.e. not requring playing long hours or tying me into commitments every day, I have also made
				some great friends through the social
				groups that form naturally in these games.
			</p><br>
			<p>Some of these online friends I also choose to see in person, through social events and boardgame nights.
				I am also currently a Dungeon Master
				in a D&D group and own many board games that I frequently whip out at said social events.
			</p>
		</div>
	</div>
</section>

<section class="supporting">
	<div class="left-box">
		<div class="item">
			<h4>Sports</h4>
			<p>Despite my obviously nerdy interests I maintain a very good knowledge of physical sports as well. This
				can mostly be attributed to the prep
				school I attended, Hill House. Instead of usual breaks and lunches, we instead did 2-3 hours a day of
				mandatory sports. We would often walk
				over to Hyde Park or the Duke of Yorks barracks to partake in a long list of sports. From this gained a
				good grasp of a large range of rules and
				basic play techniques of various sports. Of particular interest for me were fencing and cricket, the
				latter of which I was on the school team
				for. At my secondary school my interest in sports diminished somewhat, but I did develop an interest in
				basketball.
			</p><br>
			<p>It wasn't until university that I took up regular team sports again, joining a football team that met
				regularly and taking up squash with a few
				friends, as well as starting a fairly vigorous gym routine, that sadly I didnt keep up for as long as I
				should have.
			</p><br>
			<p>Currently I try to run 2-3 days a week, and do other weights on those days as well. When I'm able to I
				also like to play some squash with my partner
				and go snowboarding in Finland.
			</p>
		</div>
		<div class="item">
			<img src="/static/Images/hobbies-warhammer.jpg" alt="Sports">
		</div>
	</div>
</section>

{% endblock %}

sms_core/sms_backend/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<main>
	<div class="jumbotron">
		<div class="container">
			<h1>Website of Sandro Moszczynski </h1>
			<p>I created this website from scratch to showcase my talents and achievements. Clicking below will start
				you on a tour of each page in the website.</p>
			<br>
			<a href="{% url 'sms_backend:about' %}" class="btn-main"> Start the tour </a>
		</div>
		<p>Alternatively, you can directly go to any page from either the nav menu at the top or by clicking one of the
			pages below.</p>
	</div>

</main>
<section class="supporting">
	<div class="container_grid_index">

		<div class="item">
			<div class="sub-item-t">
				<h2>About Me</h2>
			</div>
			<div class="sub-item-p">
				<p>This is a brief introduction to me and my past. Including the "broad strokes" history of my life.</p>
			</div>
			<div class="sub-item-l">
				<a href="{% url 'sms_backend:about' %}"> Learn More</a>
			</div>

			<div class="sub-item-s"></div>

			<div class="sub-item-t">
				<h2>Hobbies</h2>
			</div>
			<div class="sub-item-p">
				<p>A brief section devoted to my non-professional interests. These include cooking, building computers,
					other artistic and creative outlets, gaming and sports.</p>
			</div>
			<div class="sub-item-l">
				<a href="{% url 'sms_backend:hobbies' %}"> Learn More</a>
			</div>
		</div>

		<div class="item">
			<div class="sub-item-t">
				<h2>Online CV</h2>
			</div>
			<div class="sub-item-p">
				<p>This is where you will find all information on my professional and academic achievements as well as
					any skills I feel are relevant to any future employers.</p>
			</div>
			<div class="sub-item-l">
				<a href="{% url 'sms_backend:cv' %}"> Learn More</a>
			</div>

			<div class="sub-item-s"></div>

			<div class="sub-item-t">
				<h2>Python Project</h2>
			</div>
			<div class="sub-item-p">
				<p>An as yet unnamed project written in Python. It will use a machine learning algorithm to trawl
					clothes and fashion site and determine the best clothing options for a person. </p>
			</div>
			<div class="sub-item-l">
				<a href="{% url 'sms_backend:python_project' %}"> Learn More</a>
			</div>
		</div>


		<div class="item">
			<div class="sub-item-t">
				<h2>Programming</h2>
			</div>
			<div class="sub-item-p">
				<p>This contains links to my Github, Codeacademy and Hacker rank pages as well as details of what each
					of the projects listed in Github contain and other programming tasks completed.</p>
			</div>
			<div class="sub-item-l">
				<a href="{% url 'sms_backend:programming' %}"> Learn More</a>
			</div>

			<div class="sub-item-s"></div>

			<div class="sub-item-t">
				<h2>C++ Project</h2>
			</div>
			<div class="sub-item-p">
				<p>An as yet unnamed project written in C++. This will take the form of a crude Minecraft clone written
					in C++. Details of versions can also be found here.</p>
			</div>
			<div class="sub-item-l">
				<a href="{% url 'sms_backend:cpp_project' %}"> Learn More</a>
			</div>
		</div>
	</div>

</section>

{% endblock %}

sms_core/sms_backend/templates/python_project.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<main>
	<div class="jumbotron">
		<div class="container">
			<h1>Un-Named Python Project</h1>
			<a href="{% url 'sms_backend:cpp_project' %}" class="btn-main"> Next Page</a>
		</div>
	</div>
</main>

<section class="supporting">
	<div class="container">
		<h3>About The Program</h3>
		<p> write about the program a bit here</p>
		<h4>Objectives of Program</h4>
		<ul>
			<li>To read a webpage</li>
			<li>To be able to distinguish between clothing items</li>
			<li>To be able to distinguish between clothing items without tags</li>
			<li>To be able to find a specific request</li>
			<li>To be able to guess a new item from memory</li>
			<li>To be able to see difference between websites tags and actual product</li>
		</ul>
	</div>
</section>

<section class="supporting">
	<div class="container">
		<h3>Current status of Program</h3>
		<p>Here is the github link to the current project</p><br>
		<a href="" class="btn-main" target="_blank"> GitHub</a>
		<h4>Recent Changelog</h4>
		<ul>
			<li>None yet</li>
		</ul>
		<h4>To do List</h4>
		<ul>
			<li>Start Program</li>
			<li>Configure way to read webpages</li>
			<li>Write agent</li>
			<li>Link agent to reading of webpages</li>
			<li>configure database structure for agent</li>
			<li>speed optimisation of agent for big data</li>
		</ul>
	</div>
</section>

{% endblock %}